### ISSUE TITLE
Release Checklist for 1.200

### ISSUE THREAD

**Issue by pathumego** [mooniak/stick-no-bills-font#50]
- [x] Credits on `README.md`
- [x] Credits on `FONTLOG.md`
- [x] Credits on  `/features/tables.fea`
- [x] Copyright notice on Repo `README.md`
- [x] Copyright notice on `OFL.txt`
- [x] Copyright on SFD sources
- [x] Copyright on UFO sources
- [x] Copyright on `/features/tables.fea`
- [x] Description (Names/ Dates)
- [x] Fontlog
- [x] Contact details
- [x] Draft the release page
- [x] rc-1 Testing
- [x] Add Thariqu to all the credit lines @paarandika 
- [ ] Check Issue Tracker for Release Milestone
- [ ] Final Feature Testing
- [ ] Version on  `build.py`
- [ ] Version and description `FONTLOG.md` 
- [ ] Update testpage

**Comment by pathumego** [comment]
@paarandika Can you start work on this? We have to do the RC-1 release today. Ill work on the fontlog before the release.

**Comment by pathumego** [comment]
@paarandika Please add Thrique in all credit lines on files and build.
