### ISSUE TITLE
Release checklist for 1.2

### ISSUE THREAD

**Issue by pathumego** [mooniak/stick-no-bills-font#87]
- [x] Credits on `README.md`
- [x] Review Sinhala
- [x] Review Latin
- [x] Reveiw Tamil
- [x] Credits on `FONTLOG.md`
- [x] Credits on  `/features/tables.fea`
- [x] Copyright notice on Repo `READM.md`
- [x] Copyright notice on `OFL.txt`
- [x] Copyright on SFD sources
- [x] Copyright on UFO sources
- [x] Copyright on `/features/tables.fea`
- [x] Version on `FONTLOG.md`
- [x] Version on  `/features/tables.fea`
- [x] Description (Names/ Dates)
- [x] Fontlog
- [x] Check Issue Tracker for Release Milestone
- [x] Final Feature Testing
- [x] rc-1 Testing

**Comment by pathumego** [comment]
DONE! https://github.com/mooniak/stick-no-bills-font/releases/tag/1.200
